// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/visitors_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVisitorRepo is a mock of VisitorRepo interface.
type MockVisitorRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVisitorRepoMockRecorder
}

// MockVisitorRepoMockRecorder is the mock recorder for MockVisitorRepo.
type MockVisitorRepoMockRecorder struct {
	mock *MockVisitorRepo
}

// NewMockVisitorRepo creates a new mock instance.
func NewMockVisitorRepo(ctrl *gomock.Controller) *MockVisitorRepo {
	mock := &MockVisitorRepo{ctrl: ctrl}
	mock.recorder = &MockVisitorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisitorRepo) EXPECT() *MockVisitorRepoMockRecorder {
	return m.recorder
}

// AddVisitor mocks base method.
func (m *MockVisitorRepo) AddVisitor(url, visitorID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddVisitor", url, visitorID)
}

// AddVisitor indicates an expected call of AddVisitor.
func (mr *MockVisitorRepoMockRecorder) AddVisitor(url, visitorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVisitor", reflect.TypeOf((*MockVisitorRepo)(nil).AddVisitor), url, visitorID)
}

// CountVisitors mocks base method.
func (m *MockVisitorRepo) CountVisitors(url string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountVisitors", url)
	ret0, _ := ret[0].(int)
	return ret0
}

// CountVisitors indicates an expected call of CountVisitors.
func (mr *MockVisitorRepoMockRecorder) CountVisitors(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountVisitors", reflect.TypeOf((*MockVisitorRepo)(nil).CountVisitors), url)
}
